"""initial schema

Revision ID: 7a5850d37d94
Revises:
Create Date: 2026-05-15 17:50:09.101210

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7a5850d37d94'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('teams', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_tokens_email'), 'api_tokens', ['email'], unique=False)
    op.create_table('audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_occurred', 'audit', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_actor_occurred', 'audit', ['actor', 'occurred_at'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity'), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('fixed_count', sa.Integer(), nullable=False),
    sa.Column('sla_breached_count', sa.Integer(), nullable=False),
    sa.Column('median_age_days', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'team', 'source', 'severity', name='uq_daily_metrics_date_team_source_sev')
    )
    op.create_index('ix_daily_metrics_date_team', 'daily_metrics', ['date', 'team'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity'), nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=True),
    sa.Column('cwe_id', sa.String(length=64), nullable=True),
    sa.Column('asset_id', sa.String(length=512), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('asset_root', sa.String(length=512), nullable=False),
    sa.Column('asset_display', sa.String(length=512), nullable=False),
    sa.Column('owner_team', sa.String(length=128), nullable=False),
    sa.Column('correlation_group_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('open', 'triaged', 'in_progress', 'fixed', 'auto_closed', 'risk_accepted', 'suppressed', name='status'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.Column('raw_payload_uri', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'native_id', name='uq_findings_source_native_id')
    )
    op.create_index('ix_findings_asset_root', 'findings', ['asset_root'], unique=False)
    op.create_index('ix_findings_correlation_group', 'findings', ['correlation_group_id'], unique=False)
    op.create_index('ix_findings_owner_team_status', 'findings', ['owner_team', 'status'], unique=False)
    op.create_index('ix_findings_source_status', 'findings', ['source', 'status'], unique=False)
    op.create_table('processed_payloads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('raw_uri', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'poll_id', name='uq_processed_payloads_source_poll')
    )
    op.create_index('ix_processed_payloads_source_processed', 'processed_payloads', ['source', 'processed_at'], unique=False)
    op.create_table('role_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('granted_by', sa.String(length=256), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'role', 'team', name='uq_role_overrides_email_role_team')
    )
    op.create_index('ix_role_overrides_email', 'role_overrides', ['email'], unique=False)
    op.create_table('finding_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('discovered', 'severity_changed', 'status_changed', 'title_changed', 'description_changed', 'fixed', 'suppressed', 'auto_closed', 'reopened', 'ownership_changed', name='event_type'), nullable=False),
    sa.Column('from_value', sa.Text(), nullable=True),
    sa.Column('to_value', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finding_events_finding_occurred', 'finding_events', ['finding_id', 'occurred_at'], unique=False)
    op.create_index('ix_finding_events_type_occurred', 'finding_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('risk_accepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('accepted_by', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_accepts_finding', 'risk_accepts', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_accepts_finding', table_name='risk_accepts')
    op.drop_table('risk_accepts')
    op.drop_index('ix_finding_events_type_occurred', table_name='finding_events')
    op.drop_index('ix_finding_events_finding_occurred', table_name='finding_events')
    op.drop_table('finding_events')
    op.drop_index('ix_role_overrides_email', table_name='role_overrides')
    op.drop_table('role_overrides')
    op.drop_index('ix_processed_payloads_source_processed', table_name='processed_payloads')
    op.drop_table('processed_payloads')
    op.drop_index('ix_findings_source_status', table_name='findings')
    op.drop_index('ix_findings_owner_team_status', table_name='findings')
    op.drop_index('ix_findings_correlation_group', table_name='findings')
    op.drop_index('ix_findings_asset_root', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_daily_metrics_date_team', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index('ix_audit_actor_occurred', table_name='audit')
    op.drop_index('ix_audit_action_occurred', table_name='audit')
    op.drop_table('audit')
    op.drop_index(op.f('ix_api_tokens_email'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
